### ISSUE TITLE
handleActivityIndicator() can be considered to be added to extensionBaseViewController

### ISSUE THREAD

**Issue by tenSunFree** [mehrankmlf/CoreAPI-iOS#2]
handleActivityIndicator() can be considered to be added to extensionBaseViewController.
![截圖 2022-10-01 下午11 40 54](https://user-images.githubusercontent.com/23090085/193417578-137baea8-4151-4a01-b8c2-42ec66d4b257.png)

In this way, LoginViewController and ListViewController can reuse handleActivityIndicator() of extensionBaseViewController uniformly.
pushToListViewController() and setupAutoLayout() may be written in the same extensionLoginViewController.
![截圖 2022-10-01 下午11 41 53](https://user-images.githubusercontent.com/23090085/193417627-ddc1c976-46d1-4c17-8f09-3c6276dc7de6.png)

**Comment by mehrankmlf** [comment]
Thank you for your cooperation, I have fixed #2
